-- Block A: Analytics schema extension for SAP HANA
--
-- Apply this after the base schema in sql/hana_setup.sql.
-- It is intentionally additive so the existing pipeline keeps working.

SET SCHEMA SOC_PIPELINE;

-- -----------------------------------------------------------------------------
-- New tables
-- -----------------------------------------------------------------------------

DO
BEGIN
    DECLARE v_count INTEGER;

    SELECT COUNT(*) INTO v_count
    FROM SYS.TABLES
    WHERE SCHEMA_NAME = CURRENT_SCHEMA
      AND TABLE_NAME = 'MODEL_RUNS';

    IF :v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE COLUMN TABLE MODEL_RUNS (
                RUN_ID NVARCHAR(64) PRIMARY KEY,
                ALGORITHM NVARCHAR(120) NOT NULL,
                FEATURE_TABLE NVARCHAR(120) NOT NULL,
                TRAINING_ROW_COUNT INTEGER NOT NULL,
                CONTAMINATION DOUBLE NOT NULL,
                STATUS NVARCHAR(40) NOT NULL,
                DETAILS_JSON NCLOB,
                STARTED_AT_UTC NVARCHAR(40) NOT NULL,
                COMPLETED_AT_UTC NVARCHAR(40)
            )
        ';
    END IF;
END;

DO
BEGIN
    DECLARE v_count INTEGER;

    SELECT COUNT(*) INTO v_count
    FROM SYS.TABLES
    WHERE SCHEMA_NAME = CURRENT_SCHEMA
      AND TABLE_NAME = 'MODEL_PREDICTIONS';

    IF :v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE COLUMN TABLE MODEL_PREDICTIONS (
                PREDICTION_ID NVARCHAR(64) PRIMARY KEY,
                RUN_ID NVARCHAR(64) NOT NULL,
                WINDOW_KEY NVARCHAR(64) NOT NULL,
                MODEL_NAME NVARCHAR(120) NOT NULL,
                SCORE DOUBLE,
                PREDICTED_LABEL NVARCHAR(32),
                CONFIDENCE DOUBLE,
                PREDICTED_AT_UTC NVARCHAR(40) NOT NULL,
                RAW_JSON NCLOB
            )
        ';
    END IF;
END;

DO
BEGIN
    DECLARE v_count INTEGER;

    SELECT COUNT(*) INTO v_count
    FROM SYS.TABLES
    WHERE SCHEMA_NAME = CURRENT_SCHEMA
      AND TABLE_NAME = 'FEATURE_DEFINITIONS';

    IF :v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE COLUMN TABLE FEATURE_DEFINITIONS (
                FEATURE_NAME NVARCHAR(120) PRIMARY KEY,
                FEATURE_GROUP NVARCHAR(80),
                DATA_TYPE NVARCHAR(40),
                DESCRIPTION NVARCHAR(1000),
                ACTIVE SMALLINT DEFAULT 1,
                CREATED_AT_UTC NVARCHAR(40) NOT NULL
            )
        ';
    END IF;
END;

DO
BEGIN
    DECLARE v_count INTEGER;

    SELECT COUNT(*) INTO v_count
    FROM SYS.TABLES
    WHERE SCHEMA_NAME = CURRENT_SCHEMA
      AND TABLE_NAME = 'ALERT_FEEDBACK';

    IF :v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE COLUMN TABLE ALERT_FEEDBACK (
                FEEDBACK_ID NVARCHAR(64) PRIMARY KEY,
                ALERT_ID NVARCHAR(64) NOT NULL,
                REVIEWER NVARCHAR(120),
                FEEDBACK_LABEL NVARCHAR(40),
                FEEDBACK_NOTES NVARCHAR(2000),
                CREATED_AT_UTC NVARCHAR(40) NOT NULL
            )
        ';
    END IF;
END;

DO
BEGIN
    DECLARE v_count INTEGER;

    SELECT COUNT(*) INTO v_count
    FROM SYS.TABLES
    WHERE SCHEMA_NAME = CURRENT_SCHEMA
      AND TABLE_NAME = 'ALERTS_EVENTS';

    IF :v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE COLUMN TABLE ALERTS_EVENTS (
                ALERT_ID NVARCHAR(64) PRIMARY KEY,
                RUN_ID NVARCHAR(64),
                DETECTED_AT_UTC NVARCHAR(64),
                ALERT_TYPE NVARCHAR(128),
                SEVERITY NVARCHAR(16),
                PAYLOAD NCLOB
            )
        ';
    END IF;
END;

-- -----------------------------------------------------------------------------
-- Dashboard views
-- -----------------------------------------------------------------------------

CREATE OR REPLACE VIEW VW_LATEST_ALERTS AS
SELECT
    ALERT_ID,
    RUN_ID,
    DETECTED_AT_UTC,
    ALERT_TYPE,
    SEVERITY,
    PAYLOAD
FROM (
    SELECT
        A.ALERT_ID,
        A.RUN_ID,
        A.DETECTED_AT_UTC,
        A.ALERT_TYPE,
        A.SEVERITY,
        A.PAYLOAD,
        ROW_NUMBER() OVER (
            ORDER BY A.DETECTED_AT_UTC DESC, A.ALERT_ID DESC
        ) AS RN
    FROM ALERTS_EVENTS A
)
WHERE RN <= 100;

CREATE OR REPLACE VIEW VW_RISK_TIMELINE AS
SELECT
    WINDOW_KEY,
    WINDOW_START,
    WINDOW_END,
    TOTAL_RECORDS,
    THREAT_SCORE,
    DETECTION_COUNT,
    ATTACK_PREDICTED,
    MODEL_AVAILABLE,
    IS_ANOMALY,
    ANOMALY_SCORE,
    ANOMALY_PERCENTILE,
    SAVED_AT_UTC
FROM WINDOW_METRICS;

CREATE OR REPLACE VIEW VW_MODEL_PERFORMANCE AS
SELECT
    MR.RUN_ID,
    MR.ALGORITHM,
    MR.FEATURE_TABLE,
    MR.TRAINING_ROW_COUNT,
    MR.CONTAMINATION,
    MR.STATUS,
    COUNT(MP.PREDICTION_ID) AS TOTAL_PREDICTIONS,
    AVG(MP.SCORE) AS AVG_SCORE,
    AVG(MP.CONFIDENCE) AS AVG_CONFIDENCE,
    SUM(
        CASE
            WHEN UPPER(COALESCE(MP.PREDICTED_LABEL, '')) IN ('ANOMALY', 'TRUE', 'YES', '1')
            THEN 1 ELSE 0
        END
    ) AS ANOMALY_PREDICTIONS,
    MAX(MP.PREDICTED_AT_UTC) AS LAST_PREDICTION_AT_UTC
FROM MODEL_RUNS MR
LEFT JOIN MODEL_PREDICTIONS MP
    ON MR.RUN_ID = MP.RUN_ID
GROUP BY
    MR.RUN_ID,
    MR.ALGORITHM,
    MR.FEATURE_TABLE,
    MR.TRAINING_ROW_COUNT,
    MR.CONTAMINATION,
    MR.STATUS;

CREATE OR REPLACE VIEW VW_ALERT_SUMMARY AS
SELECT
    ALERT_TYPE,
    SEVERITY,
    COUNT(*) AS TOTAL_ALERTS,
    MAX(DETECTED_AT_UTC) AS LAST_DETECTED_AT_UTC
FROM ALERTS_EVENTS
GROUP BY ALERT_TYPE, SEVERITY;