-- Block A step 1: tables and compatibility columns for SAP HANA
-- Run this AFTER sql/hana_setup.sql.

SET SCHEMA SOC_PIPELINE;

DO
BEGIN
    DECLARE v_count INTEGER;

    SELECT COUNT(*) INTO v_count
    FROM SYS.TABLE_COLUMNS
    WHERE SCHEMA_NAME = CURRENT_SCHEMA
      AND TABLE_NAME = 'WINDOW_METRICS'
      AND COLUMN_NAME = 'RUN_ID';

    IF :v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE WINDOW_METRICS ADD (RUN_ID NVARCHAR(64))';
    END IF;
END;

DO
BEGIN
    DECLARE v_count INTEGER;

    SELECT COUNT(*) INTO v_count
    FROM SYS.TABLE_COLUMNS
    WHERE SCHEMA_NAME = CURRENT_SCHEMA
      AND TABLE_NAME = 'WINDOW_METRICS'
      AND COLUMN_NAME = 'DETECTION_COUNT';

    IF :v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE WINDOW_METRICS ADD (DETECTION_COUNT INTEGER)';
    END IF;
END;

DO
BEGIN
    DECLARE v_count INTEGER;

    SELECT COUNT(*) INTO v_count
    FROM SYS.TABLE_COLUMNS
    WHERE SCHEMA_NAME = CURRENT_SCHEMA
      AND TABLE_NAME = 'WINDOW_FEATURES'
      AND COLUMN_NAME = 'RUN_ID';

    IF :v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE WINDOW_FEATURES ADD (RUN_ID NVARCHAR(64))';
    END IF;
END;

DO
BEGIN
    DECLARE v_count INTEGER;

    SELECT COUNT(*) INTO v_count
    FROM SYS.TABLES
    WHERE SCHEMA_NAME = CURRENT_SCHEMA
      AND TABLE_NAME = 'MODEL_RUNS';

    IF :v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE COLUMN TABLE MODEL_RUNS (
                RUN_ID NVARCHAR(64) PRIMARY KEY,
                ALGORITHM NVARCHAR(120) NOT NULL,
                FEATURE_TABLE NVARCHAR(120) NOT NULL,
                TRAINING_ROW_COUNT INTEGER NOT NULL,
                CONTAMINATION DOUBLE NOT NULL,
                STATUS NVARCHAR(40) NOT NULL,
                DETAILS_JSON NCLOB,
                STARTED_AT_UTC NVARCHAR(40) NOT NULL,
                COMPLETED_AT_UTC NVARCHAR(40)
            )
        ';
    END IF;
END;

DO
BEGIN
    DECLARE v_count INTEGER;

    SELECT COUNT(*) INTO v_count
    FROM SYS.TABLES
    WHERE SCHEMA_NAME = CURRENT_SCHEMA
      AND TABLE_NAME = 'MODEL_PREDICTIONS';

    IF :v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE COLUMN TABLE MODEL_PREDICTIONS (
                PREDICTION_ID NVARCHAR(64) PRIMARY KEY,
                RUN_ID NVARCHAR(64) NOT NULL,
                WINDOW_KEY NVARCHAR(64) NOT NULL,
                MODEL_NAME NVARCHAR(120) NOT NULL,
                SCORE DOUBLE,
                PREDICTED_LABEL NVARCHAR(32),
                CONFIDENCE DOUBLE,
                PREDICTED_AT_UTC NVARCHAR(40) NOT NULL,
                RAW_JSON NCLOB
            )
        ';
    END IF;
END;

DO
BEGIN
    DECLARE v_count INTEGER;

    SELECT COUNT(*) INTO v_count
    FROM SYS.TABLES
    WHERE SCHEMA_NAME = CURRENT_SCHEMA
      AND TABLE_NAME = 'FEATURE_DEFINITIONS';

    IF :v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE COLUMN TABLE FEATURE_DEFINITIONS (
                FEATURE_NAME NVARCHAR(120) PRIMARY KEY,
                FEATURE_GROUP NVARCHAR(80),
                DATA_TYPE NVARCHAR(40),
                DESCRIPTION NVARCHAR(1000),
                ACTIVE SMALLINT DEFAULT 1,
                CREATED_AT_UTC NVARCHAR(40) NOT NULL
            )
        ';
    END IF;
END;

DO
BEGIN
    DECLARE v_count INTEGER;

    SELECT COUNT(*) INTO v_count
    FROM SYS.TABLES
    WHERE SCHEMA_NAME = CURRENT_SCHEMA
      AND TABLE_NAME = 'ALERT_FEEDBACK';

    IF :v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE COLUMN TABLE ALERT_FEEDBACK (
                FEEDBACK_ID NVARCHAR(64) PRIMARY KEY,
                ALERT_ID NVARCHAR(64) NOT NULL,
                REVIEWER NVARCHAR(120),
                FEEDBACK_LABEL NVARCHAR(40),
                FEEDBACK_NOTES NVARCHAR(2000),
                CREATED_AT_UTC NVARCHAR(40) NOT NULL
            )
        ';
    END IF;
END;

DO
BEGIN
    DECLARE v_count INTEGER;

    SELECT COUNT(*) INTO v_count
    FROM SYS.TABLES
    WHERE SCHEMA_NAME = CURRENT_SCHEMA
      AND TABLE_NAME = 'ALERTS_EVENTS';

    IF :v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE COLUMN TABLE ALERTS_EVENTS (
                ALERT_ID NVARCHAR(64) PRIMARY KEY,
                RUN_ID NVARCHAR(64),
                DETECTED_AT_UTC NVARCHAR(64),
                ALERT_TYPE NVARCHAR(128),
                SEVERITY NVARCHAR(16),
                PAYLOAD NCLOB
            )
        ';
    END IF;
END;
