-- Block A step 2: analytics views for SAP HANA
-- Run this AFTER sql/migrations/001_analytics_extension_tables.sql.

SET SCHEMA SOC_PIPELINE;

CREATE OR REPLACE VIEW VW_LATEST_ALERTS AS
SELECT
    ALERT_ID,
    RUN_ID,
    DETECTED_AT_UTC,
    ALERT_TYPE,
    SEVERITY,
    PAYLOAD
FROM (
    SELECT
        A.ALERT_ID,
        A.RUN_ID,
        A.DETECTED_AT_UTC,
        A.ALERT_TYPE,
        A.SEVERITY,
        A.PAYLOAD,
        ROW_NUMBER() OVER (
            ORDER BY A.DETECTED_AT_UTC DESC, A.ALERT_ID DESC
        ) AS RN
    FROM "SOC_PIPELINE"."ALERTS_EVENTS" A
)
WHERE RN <= 100;

CREATE OR REPLACE VIEW VW_RISK_TIMELINE AS
SELECT *
FROM "SOC_PIPELINE"."WINDOW_METRICS";

CREATE OR REPLACE VIEW VW_MODEL_PERFORMANCE AS
SELECT
    MR.*,
    COALESCE(P.TOTAL_PREDICTIONS, 0) AS TOTAL_PREDICTIONS,
    COALESCE(P.AVG_SCORE, 0) AS AVG_SCORE,
    COALESCE(P.AVG_CONFIDENCE, 0) AS AVG_CONFIDENCE,
    COALESCE(P.ANOMALY_PREDICTIONS, 0) AS ANOMALY_PREDICTIONS,
    P.LAST_PREDICTION_AT_UTC
FROM "SOC_PIPELINE"."MODEL_RUNS" MR
LEFT JOIN (
    SELECT
        RUN_ID,
        COUNT(PREDICTION_ID) AS TOTAL_PREDICTIONS,
        AVG(SCORE) AS AVG_SCORE,
        AVG(CONFIDENCE) AS AVG_CONFIDENCE,
        SUM(
            CASE
                WHEN UPPER(COALESCE(PREDICTED_LABEL, '')) IN ('ANOMALY', 'TRUE', 'YES', '1')
                THEN 1 ELSE 0
            END
        ) AS ANOMALY_PREDICTIONS,
        MAX(PREDICTED_AT_UTC) AS LAST_PREDICTION_AT_UTC
    FROM "SOC_PIPELINE"."MODEL_PREDICTIONS"
    GROUP BY RUN_ID
) P
    ON MR.RUN_ID = P.RUN_ID;

CREATE OR REPLACE VIEW VW_ALERT_SUMMARY AS
SELECT
    ALERT_TYPE,
    SEVERITY,
    COUNT(*) AS TOTAL_ALERTS,
    MAX(DETECTED_AT_UTC) AS LAST_DETECTED_AT_UTC
FROM "SOC_PIPELINE"."ALERTS_EVENTS"
GROUP BY ALERT_TYPE, SEVERITY;
