CREATE SCHEMA SOC_PIPELINE;
SET SCHEMA SOC_PIPELINE;

CREATE COLUMN TABLE RAW_LOGS (
    LOG_ID NVARCHAR(255) PRIMARY KEY,
    WINDOW_KEY NVARCHAR(64) NOT NULL,
    WINDOW_START_UTC NVARCHAR(40),
    WINDOW_END_UTC NVARCHAR(40),
    LOG_TIMESTAMP_UTC NVARCHAR(80),
    SAP_FUNCTION_LOG_TYPE NVARCHAR(80),
    IS_LLM_LOG SMALLINT,
    IS_SYSTEM_LOG SMALLINT,
    CLIENT_IP NVARCHAR(128),
    SERVICE_ID NVARCHAR(255),
    HTTP_STATUS_CODE INTEGER,
    LLM_MODEL_ID NVARCHAR(255),
    LLM_STATUS NVARCHAR(80),
    LLM_COST_USD DOUBLE,
    LLM_RESPONSE_TIME_MS DOUBLE,
    RAW_PAYLOAD_JSON NCLOB
);

CREATE COLUMN TABLE WINDOW_METRICS (
    WINDOW_KEY NVARCHAR(64) PRIMARY KEY,
    WINDOW_START_UTC NVARCHAR(40),
    WINDOW_END_UTC NVARCHAR(40),
    TOTAL_RECORDS INTEGER,
    SYSTEM_LOG_COUNT INTEGER,
    LLM_LOG_COUNT INTEGER,
    ERROR_COUNT INTEGER,
    SECURITY_COUNT INTEGER,
    WARNING_COUNT INTEGER,
    AUDIT_COUNT INTEGER,
    DEBUG_COUNT INTEGER,
    PERF_COUNT INTEGER,
    HTTP_4XX_COUNT INTEGER,
    HTTP_5XX_COUNT INTEGER,
    HTTP_4XX_RATE DOUBLE,
    HTTP_5XX_RATE DOUBLE,
     INTEGER,
    UNIQUE_IP_SERVICE_PAIRS INTEGER,
    MAX_EVENTS_FROM_SINGLE_IP INTEGER,
    MAX_SERVICES_FROM_SINGLE_IP INTEGER,
    SUSPICIOUS_IP_COUNT INTEGER,
    AVG_EVENTS_PER_IP DOUBLE,
    AVG_EVENTS_PER_SERVICE DOUBLE,
    TOP_IP_EVENT_SHARE DOUBLE,
    TOP_SERVICE_EVENT_SHARE DOUBLE,
    SUSPICIOUS_IP_RATIO DOUBLE,
    IP_BURST_RATIO DOUBLE,
    PAIR_REUSE_RATIO DOUBLE,
    CLIENT_IP_ENTROPY DOUBLE,
    SERVICE_ENTROPY DOUBLE,
    LLM_REQUEST_COUNT INTEGER,
    LLM_TIMEOUT_COUNT INTEGER,
    LLM_ERROR_COUNT INTEGER,
    LLM_COST_PER_REQUEST DOUBLE,
    LLM_MODEL_ENTROPY DOUBLE,
    AVG_LLM_LATENCY_MS DOUBLE,
    P95_LLM_LATENCY_MS DOUBLE,
    TOTAL_LLM_COST_USD DOUBLE,
    SYSTEM_ERROR_RATE DOUBLE,
    LLM_TIMEOUT_RATE DOUBLE,
    LLM_ERROR_RATE DOUBLE,
    LLM_TIMEOUT_PLUS_ERROR_RATE DOUBLE,
    SECURITY_ERROR_RATIO DOUBLE,
    DELTA_TOTAL_RECORDS DOUBLE,
    DELTA_ERROR_COUNT DOUBLE,
    DELTA_SECURITY_COUNT DOUBLE,
    DELTA_AVG_LLM_LATENCY_MS DOUBLE,
    DELTA_P95_LLM_LATENCY_MS DOUBLE,
    DELTA_TOTAL_LLM_COST_USD DOUBLE,
    DELTA_TOP_IP_EVENT_SHARE DOUBLE,
    DELTA_LLM_TIMEOUT_PLUS_ERROR_RATE DOUBLE,
    RULE_SCORE INTEGER,
    FINAL_SCORE INTEGER,
    DECISION_SOURCE NVARCHAR(40),
    ML_MODEL_AVAILABLE SMALLINT,
    ML_TRAINING_ROW_COUNT INTEGER,
    ML_ANOMALY_SCORE DOUBLE,
    ML_CONFIDENCE_SCORE DOUBLE,
    ML_IS_ANOMALY SMALLINT,
    THREAT_SCORE INTEGER,
    DETECTION_COUNT INTEGER,
    ATTACK_PREDICTED SMALLINT,
    SUMMARY_JSON NCLOB,
    SAVED_AT_UTC NVARCHAR(40)
);

CREATE COLUMN TABLE DETECTIONS (
    DETECTION_ID NVARCHAR(64) PRIMARY KEY,
    WINDOW_KEY NVARCHAR(64) NOT NULL,
    RULE_NAME NVARCHAR(120) NOT NULL,
    SEVERITY NVARCHAR(20) NOT NULL,
    SCORE INTEGER NOT NULL,
    MESSAGE NVARCHAR(1000) NOT NULL,
    CONTEXT_JSON NCLOB,
    DETECTED_AT_UTC NVARCHAR(40) NOT NULL
);

CREATE COLUMN TABLE TRAINING_LABELS (
    WINDOW_KEY NVARCHAR(64) PRIMARY KEY,
    LABEL_ATTACK SMALLINT NOT NULL,
    LABEL_SOURCE NVARCHAR(120),
    LABEL_NOTES NVARCHAR(1000),
    LABELED_AT_UTC NVARCHAR(40) NOT NULL
);

CREATE COLUMN TABLE MODEL_RUNS (
    RUN_ID NVARCHAR(64) PRIMARY KEY,
    ALGORITHM NVARCHAR(120) NOT NULL,
    FEATURE_TABLE NVARCHAR(120) NOT NULL,
    TRAINING_ROW_COUNT INTEGER NOT NULL,
    CONTAMINATION DOUBLE NOT NULL,
    STATUS NVARCHAR(40) NOT NULL,
    DETAILS_JSON NCLOB,
    STARTED_AT_UTC NVARCHAR(40) NOT NULL,
    COMPLETED_AT_UTC NVARCHAR(40)
);

CREATE COLUMN TABLE MODEL_SCORES (
    RUN_ID NVARCHAR(64) NOT NULL,
    WINDOW_KEY NVARCHAR(64) NOT NULL,
    ANOMALY_SCORE DOUBLE,
    IS_ANOMALY SMALLINT,
    RAW_JSON NCLOB,
    PRIMARY KEY (RUN_ID, WINDOW_KEY)
);
