-- Triage rapido: pipeline sin prender / sin ingesta por ~3 dias.
-- SAP HANA, solo lectura.
-- Schema esperado: SOC_PIPELINE.

-- 1) Ultimo latido de cada tabla importante.
SELECT '01_ULTIMO_LATIDO' AS SECTION FROM DUMMY;

SELECT 'INGEST_RUNS.STARTED_AT_UTC' AS SIGNAL, MAX(STARTED_AT_UTC) AS LAST_SEEN
FROM "SOC_PIPELINE"."INGEST_RUNS"
UNION ALL
SELECT 'INGEST_RUNS.ENDED_AT_UTC', MAX(ENDED_AT_UTC)
FROM "SOC_PIPELINE"."INGEST_RUNS"
UNION ALL
SELECT 'RAW_LOGS.LOG_TS', MAX(LOG_TS)
FROM "SOC_PIPELINE"."RAW_LOGS"
UNION ALL
SELECT 'RAW_LOGS.INGESTED_AT', MAX(INGESTED_AT)
FROM "SOC_PIPELINE"."RAW_LOGS"
UNION ALL
SELECT 'WINDOW_METRICS.SAVED_AT_UTC', MAX(SAVED_AT_UTC)
FROM "SOC_PIPELINE"."WINDOW_METRICS"
UNION ALL
SELECT 'ALERTS_EVENTS.DETECTED_AT_UTC', MAX(DETECTED_AT_UTC)
FROM "SOC_PIPELINE"."ALERTS_EVENTS";

-- 2) Ultimos 20 runs. Si aqui no hay nada reciente, el worker no esta corriendo
-- o no puede llegar a SAP SOC antes de guardar el run.
SELECT '02_ULTIMOS_RUNS' AS SECTION FROM DUMMY;

SELECT
    RUN_ID,
    STATUS,
    STARTED_AT_UTC,
    ENDED_AT_UTC,
    DURATION_SECONDS,
    TOTAL_PAGES_EXPECTED,
    TOTAL_PAGES_FETCHED,
    TOTAL_RECORDS_INFO,
    TOTAL_RECORDS_FETCHED,
    ERROR_MESSAGE
FROM "SOC_PIPELINE"."INGEST_RUNS"
ORDER BY STARTED_AT_UTC DESC
LIMIT 20;

-- 3) Runs fallidos recientes. Esto suele revelar token vencido, API caida,
-- timeout, DNS, permisos o schema roto.
SELECT '03_FALLOS_RECIENTES' AS SECTION FROM DUMMY;

SELECT
    RUN_ID,
    STARTED_AT_UTC,
    ENDED_AT_UTC,
    DURATION_SECONDS,
    ERROR_MESSAGE
FROM "SOC_PIPELINE"."INGEST_RUNS"
WHERE STATUS <> 'success'
ORDER BY STARTED_AT_UTC DESC
LIMIT 30;

-- 4) Conteo de actividad en los ultimos 3 dias.
-- Como las fechas se guardan en NVARCHAR ISO-like, comparamos por fecha YYYY-MM-DD.
SELECT '04_ACTIVIDAD_ULTIMOS_3_DIAS' AS SECTION FROM DUMMY;

SELECT 'INGEST_RUNS' AS TABLE_NAME, COUNT(*) AS ROWS_LAST_3_DAYS
FROM "SOC_PIPELINE"."INGEST_RUNS"
WHERE SUBSTRING(COALESCE(STARTED_AT_UTC, ENDED_AT_UTC), 1, 10)
    >= TO_NVARCHAR(ADD_DAYS(CURRENT_UTCTIMESTAMP, -3), 'YYYY-MM-DD')
UNION ALL
SELECT 'RAW_LOGS', COUNT(*)
FROM "SOC_PIPELINE"."RAW_LOGS"
WHERE SUBSTRING(COALESCE(LOG_TS, INGESTED_AT), 1, 10)
    >= TO_NVARCHAR(ADD_DAYS(CURRENT_UTCTIMESTAMP, -3), 'YYYY-MM-DD')
UNION ALL
SELECT 'WINDOW_METRICS', COUNT(*)
FROM "SOC_PIPELINE"."WINDOW_METRICS"
WHERE SUBSTRING(COALESCE(SAVED_AT_UTC, WINDOW_START), 1, 10)
    >= TO_NVARCHAR(ADD_DAYS(CURRENT_UTCTIMESTAMP, -3), 'YYYY-MM-DD')
UNION ALL
SELECT 'ALERTS_EVENTS', COUNT(*)
FROM "SOC_PIPELINE"."ALERTS_EVENTS"
WHERE SUBSTRING(DETECTED_AT_UTC, 1, 10)
    >= TO_NVARCHAR(ADD_DAYS(CURRENT_UTCTIMESTAMP, -3), 'YYYY-MM-DD');

-- 5) Si hay RAW_LOGS recientes pero no WINDOW_METRICS, el cuello esta en
-- normalizacion/deteccion/persistencia de ventanas.
SELECT '05_RAW_RECIENTE_SIN_METRICAS' AS SECTION FROM DUMMY;

SELECT
    RAW_BY_HOUR.HOUR_UTC,
    RAW_BY_HOUR.RAW_LOGS,
    COALESCE(METRICS_BY_HOUR.METRIC_WINDOWS, 0) AS METRIC_WINDOWS
FROM (
    SELECT
        SUBSTRING(COALESCE(LOG_TS, INGESTED_AT), 1, 13) || ':00' AS HOUR_UTC,
        COUNT(*) AS RAW_LOGS
    FROM "SOC_PIPELINE"."RAW_LOGS"
    WHERE SUBSTRING(COALESCE(LOG_TS, INGESTED_AT), 1, 10)
        >= TO_NVARCHAR(ADD_DAYS(CURRENT_UTCTIMESTAMP, -3), 'YYYY-MM-DD')
    GROUP BY SUBSTRING(COALESCE(LOG_TS, INGESTED_AT), 1, 13)
) RAW_BY_HOUR
LEFT JOIN (
    SELECT
        SUBSTRING(COALESCE(WINDOW_START, SAVED_AT_UTC), 1, 13) || ':00' AS HOUR_UTC,
        COUNT(*) AS METRIC_WINDOWS
    FROM "SOC_PIPELINE"."WINDOW_METRICS"
    WHERE SUBSTRING(COALESCE(WINDOW_START, SAVED_AT_UTC), 1, 10)
        >= TO_NVARCHAR(ADD_DAYS(CURRENT_UTCTIMESTAMP, -3), 'YYYY-MM-DD')
    GROUP BY SUBSTRING(COALESCE(WINDOW_START, SAVED_AT_UTC), 1, 13)
) METRICS_BY_HOUR
    ON RAW_BY_HOUR.HOUR_UTC = METRICS_BY_HOUR.HOUR_UTC
WHERE COALESCE(METRICS_BY_HOUR.METRIC_WINDOWS, 0) = 0
ORDER BY RAW_BY_HOUR.HOUR_UTC DESC;

-- 6) Volumen por hora: gaps claros o ultima hora con datos.
SELECT '06_VOLUMEN_RAW_POR_HORA' AS SECTION FROM DUMMY;

SELECT
    SUBSTRING(COALESCE(LOG_TS, INGESTED_AT), 1, 13) || ':00' AS HOUR_UTC,
    COUNT(*) AS RAW_LOGS,
    SUM(CASE WHEN IS_SYSTEM_LOG = 1 THEN 1 ELSE 0 END) AS SYSTEM_LOGS,
    SUM(CASE WHEN IS_LLM_LOG = 1 THEN 1 ELSE 0 END) AS LLM_LOGS
FROM "SOC_PIPELINE"."RAW_LOGS"
WHERE COALESCE(LOG_TS, INGESTED_AT) IS NOT NULL
GROUP BY SUBSTRING(COALESCE(LOG_TS, INGESTED_AT), 1, 13)
ORDER BY HOUR_UTC DESC
LIMIT 72;

-- 7) Salud del schema minimo que usa el runtime.
-- Si falta alguna de estas columnas, la app puede arrancar pero fallar al escribir.
SELECT '07_SCHEMA_RUNTIME_MINIMO' AS SECTION FROM DUMMY;

SELECT
    REQUIRED.TABLE_NAME,
    REQUIRED.COLUMN_NAME,
    CASE WHEN C.COLUMN_NAME IS NULL THEN 'MISSING' ELSE 'OK' END AS STATUS
FROM (
    SELECT 'RAW_LOGS' AS TABLE_NAME, 'LOG_ID' AS COLUMN_NAME FROM DUMMY
    UNION ALL SELECT 'RAW_LOGS', 'LOG_TS' FROM DUMMY
    UNION ALL SELECT 'RAW_LOGS', 'PAYLOAD' FROM DUMMY
    UNION ALL SELECT 'RAW_LOGS', 'INGESTED_AT' FROM DUMMY
    UNION ALL SELECT 'INGEST_RUNS', 'RUN_ID' FROM DUMMY
    UNION ALL SELECT 'INGEST_RUNS', 'STATUS' FROM DUMMY
    UNION ALL SELECT 'INGEST_RUNS', 'STARTED_AT_UTC' FROM DUMMY
    UNION ALL SELECT 'INGEST_RUNS', 'ERROR_MESSAGE' FROM DUMMY
    UNION ALL SELECT 'WINDOW_METRICS', 'WINDOW_KEY' FROM DUMMY
    UNION ALL SELECT 'WINDOW_METRICS', 'SUMMARY_JSON' FROM DUMMY
    UNION ALL SELECT 'WINDOW_METRICS', 'SAVED_AT_UTC' FROM DUMMY
    UNION ALL SELECT 'WINDOW_FEATURES', 'WINDOW_KEY' FROM DUMMY
    UNION ALL SELECT 'ALERTS_EVENTS', 'ALERT_ID' FROM DUMMY
    UNION ALL SELECT 'ALERTS_EVENTS', 'DETECTED_AT_UTC' FROM DUMMY
) REQUIRED
LEFT JOIN SYS.TABLE_COLUMNS C
    ON C.SCHEMA_NAME = 'SOC_PIPELINE'
   AND C.TABLE_NAME = REQUIRED.TABLE_NAME
   AND C.COLUMN_NAME = REQUIRED.COLUMN_NAME
ORDER BY REQUIRED.TABLE_NAME, REQUIRED.COLUMN_NAME;

-- 8) Bloqueos activos sobre tablas del pipeline.
SELECT '08_LOCKS_ACTIVOS' AS SECTION FROM DUMMY;

SELECT
    CONNECTION_ID,
    TRANSACTION_ID,
    LOCK_MODE,
    LOCK_STATUS,
    SCHEMA_NAME,
    TABLE_NAME,
    OBJECT_NAME
FROM SYS.M_TABLE_LOCKS
WHERE SCHEMA_NAME = 'SOC_PIPELINE'
ORDER BY TABLE_NAME, LOCK_STATUS;
